### ISSUE TITLE
Make 1173 planned issues into placeholder issues

### ISSUE THREAD

**Issue by ronaldtse** [ituob/ituob.org#2]
Planned issues from 1173 to be made into placeholder issues.

Since I already got them converted it's easier for copy and paste 😉 

```yaml
  - id: 1175
    publication_date: 2019-07-01
    cutoff_date: 2019-06-14
  - id: 1176
    publication_date: 2019-07-15
    cutoff_date: 2019-06-28
  - id: 1177
    publication_date: 2019-08-01
    cutoff_date: 2019-07-15
  - id: 1178
    publication_date: 2019-08-15
    cutoff_date: 2019-07-31
  - id: 1179
    publication_date: 2019-09-01
    cutoff_date: 2019-08-16
  - id: 1180
    publication_date: 2019-09-15
    cutoff_date: 2019-08-30
  - id: 1181
    publication_date: 2019-10-01
    cutoff_date: 2019-09-16
  - id: 1182
    publication_date: 2019-10-15
    cutoff_date: 2019-10-01
  - id: 1183
    publication_date: 2019-11-01
    cutoff_date: 2019-10-15
  - id: 1184
    publication_date: 2019-11-15
    cutoff_date: 2019-11-01
  - id: 1185
    publication_date: 2019-12-01
    cutoff_date: 2019-11-15
  - id: 1186
    publication_date: 2019-12-15
    cutoff_date: 2019-12-02
```
