### ISSUE TITLE
Update freeform issue contents rendering, replacing included AsciiDoc files with ProseMirror structures

### ISSUE THREAD

**Issue by strogonoff** [ituob/ituob.org#3]
We could render it to HTML during editing from the ITU OB editor app, but perhaps it’s better if only structured representation is stored, so that rendering of such structure into HTML & other deliverables is handled by site build.

Sample amendment specifying freeform contents:

```
  - type: amendment
    target:
      publication: E118_IIN
      position_on: 2018-12-01
    contents:
      type: doc
      content:
        - type: paragraph
          content:
            - type: text
              text: foo
            - type: text
              marks:
                - type: em
              text: bar
```

**Comment by ronaldtse** [comment]
AsciiDoc (including tables) could technically be parsed into a deterministic structured format.

Writing text like this will be very painful...
```yaml
    contents:
      type: doc
      content:
        - type: paragraph
          content:
            - type: text
              text: foo
            - type: text
              marks:
                - type: em
              text: bar
```

**Comment by strogonoff** [comment]
> AsciiDoc (including tables) could technically be parsed into a deterministic structured format.
> 
> Writing text like this will be very painful...
> 
> ```yaml
>     contents:
>       type: doc
>       content:
>         - type: paragraph
>           content:
>             - type: text
>               text: foo
>             - type: text
>               marks:
>                 - type: em
>               text: bar
> ```

@ronaldtse I just noticed your comment. You prefer that we store, _in the repository_ (note that it’s not visible to site visitors, they’ll see rendered content), text editor data in a more “human-authorable” way than YAML structured this way?

**Comment by ronaldtse** [comment]
@strogonoff I'd rather we store AsciiDoc in YAML in the repository. For example, it's easy to transform between:

```yaml
    contents:
      type: doc
      content:
        - type: paragraph
          content:
            - type: text
              text: foo
            - type: text
              marks:
                - type: em
              text: bar
```

and

```adoc
foo _bar_
```
